name: stack-osdev

services:
  oracle-sql-developer:
    #image: ozkr0124/oracle-sql-developer:1.0.0
    build:
      context: .
      dockerfile: Dockerfile.arm64
    restart: unless-stopped
    platform: linux/arm64
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - TZ=America/Bogota
    ports:
      - 8444:8444
    volumes:
      - sqldeveloper-data:/config/.sqldeveloper

volumes:
  sqldeveloper-data: