name: stack-osdev

services:
  oracle-sql-developer:
    image: ozkr0124/oracle-sql-developer:1.0.0-amd64
    # build:
    #   context: .
    #   dockerfile: Dockerfile.amd64
    restart: unless-stopped
    platform: linux/amd64
    security_opt:
      - seccomp:unconfined #optional
    ports:
      - 8444:8444
    environment:
      - TZ=America/Bogota
    volumes:
      - sqldeveloper-data:/root/.sqldeveloper

volumes:
  sqldeveloper-data: